
/* ============================================================================
   Insights automatiques : on calcule un large eventail de statistiques et on
   classe ce qui est remarquable (idee de Foresight, Demiralp, Haas,
   Parthasarathy & Pedapati 2017, et de Voyager, Wongsuphasawat et al. 2016).
   Chaque insight porte un score dans [0, 1], une phrase, un mini-graphique et
   une action qui ouvre la bonne vue.
   ============================================================================ */
const INSIGHT_KINDS = {
  structure: { l: "Structure", ic: "◈", c: "var(--a3)" }, corr: { l: "Corrélation", ic: "↗", c: "var(--a2)" }, indirect: { l: "Lien indirect", ic: "⤳", c: "var(--a3)" },
  nonlin: { l: "Non monotone", ic: "∿", c: "var(--g5)" }, curve: { l: "Courbure", ic: "⌒", c: "var(--g7)" }, redund: { l: "Redondance", ic: "≡", c: "var(--g7)" }, skew: { l: "Asymétrie", ic: "◿", c: "var(--amber)" },
  bimodal: { l: "Bimodalité", ic: "⩘", c: "var(--g5)" }, outlier: { l: "Atypiques", ic: "✦", c: "var(--a1)" }, clusters: { l: "Classes", ic: "⬡", c: "var(--g6)" },
  groups: { l: "Groupes", ic: "▦", c: "var(--g4)" }, hidden: { l: "Hors écran", ic: "⌬", c: "var(--a3)" }, missing: { l: "Données", ic: "◌", c: "var(--warn)" },
  shape: { l: "Forme", ic: "⁘", c: "var(--g7)" }, assoc: { l: "Association", ic: "⇄", c: "var(--a2)" },
};
function buildInsights(res, table, hc, scag) {
  const I = [], add = o => I.push(o), rows = res.rowsKept ? res.rowsKept.map(i => table.rows[i]) : table.rows;
  // structure globale
  const S = Math.min(res.q, 3), out3 = 100 - res.cum[S - 1];
  add({ kind: "structure", score: 0.55, title: `${pl(res.nAxes, "axe résume", "axes résument")} ${pc(res.cum[res.nAxes - 1])} de l'information`, text: res.method === "ACP" ? `Kaiser retient ${pl(res.rule, "axe")}, le coude ${pl(res.coude, "axe")}. ${res.pct[0] >= 60 ? "L'axe 1 domine : effet taille probable." : "Aucun axe n'écrase les autres."}` : res.method === "ACM" ? `En ACM les pourcentages d'inertie sont faibles par construction ; ${pl(res.rule, "axe dépasse", "axes dépassent")} le seuil 1/K.` : `La liaison est ${res.pval < 0.05 ? "significative" : "non significative"} (χ² = ${fr(res.chi2, 1)}, p ${res.pval < 0.001 ? "< 0,001" : "= " + fr(res.pval, 3)}).`, mini: { type: "scree" }, act: { tab: "axes" } });
  if (res.q > 3 && out3 >= 20) add({ kind: "hidden", score: clamp(out3 / 60, 0.3, 0.9), title: `${pc(out3)} de l'information est hors de la 3D`, text: `La vue 3D ne montre que les ${S} premiers axes sur ${res.q}. Le Tour de l'hyperespace fait tourner le nuage dans toutes ses dimensions pour voir le reste.`, mini: { type: "bars", data: res.pct.slice(0, 10).map((p, k) => ({ l: String(k + 1), v: p, c: k < 3 ? `var(--a${k + 1})` : "var(--faint)" })) }, act: { hyper: "tour" } });
  if (res.method === "ACP") {
    const pr = [], P = partialCorr(res.R); for (let i = 0; i < res.p; i++) for (let j = i + 1; j < res.p; j++) pr.push({ i, j, r: res.R[i][j], pc: P ? P[i][j] : null });
    pr.slice().sort((a, b) => Math.abs(b.r) - Math.abs(a.r)).slice(0, 3).filter(o => Math.abs(o.r) >= 0.5).forEach(o => add({ kind: "corr", score: Math.abs(o.r) * 0.95, key: `pair${o.i}-${o.j}`,
      title: `${res.vars[o.i]} et ${res.vars[o.j]} ${o.r > 0 ? "évoluent ensemble" : "s'opposent"}`, text: `Corrélation r = ${frs(o.r)} : ${pc(o.r * o.r * 100, 0)} de la variance de l'une est liée à l'autre. ${P ? (Math.abs(o.pc) >= 0.3 ? `Le lien reste direct une fois les autres variables fixées (partielle ${frs(o.pc)}).` : `Mais il s'affaiblit une fois les autres variables fixées (partielle ${frs(o.pc)}).`) : ""}`,
      mini: { type: "scatter", i: o.i, j: o.j }, act: { pair: [o.i, o.j] } }));
    if (P) pr.filter(o => Math.abs(o.r) >= 0.4 && Math.abs(o.pc) < 0.15).sort((a, b) => Math.abs(b.r) - Math.abs(a.r)).slice(0, 2).forEach(o => {
      const z = range(res.p).filter(k => k !== o.i && k !== o.j).sort((a, b) => Math.abs(res.R[o.i][b] * res.R[o.j][b]) - Math.abs(res.R[o.i][a] * res.R[o.j][a]))[0];
      add({ kind: "indirect", score: 0.5 + 0.5 * (Math.abs(o.r) - Math.abs(o.pc)), key: `pair${o.i}-${o.j}`, title: `Le lien ${res.vars[o.i]} – ${res.vars[o.j]} est indirect`, text: `Corrélés à r = ${frs(o.r)}, ils ne le sont presque plus à autres variables fixées (partielle ${frs(o.pc)}). Le lien passe sans doute par ${res.vars[z]} (r = ${frs(res.R[o.i][z])} et ${frs(res.R[o.j][z])}).`, mini: { type: "scatter", i: o.i, j: o.j }, act: { tab: "hyper" } }); });
    if (P) { const Pi = invSym(res.R); if (Pi) Pi.forEach((row, j) => { const vif = row[j], r2 = 1 - 1 / vif; if (vif >= 5) add({ kind: "redund", score: clamp(r2, 0.5, 0.95), title: `${res.vars[j]} est presque redondante`, text: `${pc(r2 * 100, 0)} de sa variance est expliquée par les autres variables (VIF = ${fr(vif, 1)}). Elle apporte peu d'information propre à l'analyse.`, mini: { type: "gauge", v: r2 }, act: { tab: "variables" } }); }); }
    (scag || []).forEach(s => {
      if (s.nonmono >= 0.1 && s.dcorR >= 0.3) add({ kind: "nonlin", score: clamp(0.5 + s.nonmono * 1.6, 0, 0.97), key: `pair${s.i}-${s.j}`, vars: [s.i, s.j], title: `Relation non monotone : ${res.vars[s.i]} × ${res.vars[s.j]}`, text: `Un lien existe (corrélation de distance sur les rangs = ${fr(s.dcorR)}) mais il change de sens en cours de route, en U ou en cloche : Pearson (r = ${frs(s.pearson)}) et Spearman (ρ = ${frs(s.spearman)}) le manquent, et l'ACP, qui ne voit que le linéaire, aussi.`, mini: { type: "scatter", i: s.i, j: s.j }, act: { pair: [s.i, s.j] } });
      else if (s.curve >= 0.1 && Math.abs(s.spearman) >= 0.4) add({ kind: "curve", score: clamp(0.4 + s.curve * 1.5, 0, 0.85), key: `pair${s.i}-${s.j}`, vars: [s.i, s.j], title: `Lien monotone mais courbe : ${res.vars[s.i]} × ${res.vars[s.j]}`, text: `Spearman (ρ = ${frs(s.spearman)}) dépasse nettement Pearson (r = ${frs(s.pearson)}) : l'une augmente avec l'autre, mais pas en ligne droite. Un logarithme ou un passage aux rangs rendrait le lien linéaire.`, mini: { type: "scatter", i: s.i, j: s.j }, act: { pair: [s.i, s.j] } });
      if (s.clumpy >= 0.6) add({ kind: "shape", score: 0.35 + 0.4 * s.clumpy, key: `pair${s.i}-${s.j}`, vars: [s.i, s.j], title: `${res.vars[s.i]} × ${res.vars[s.j]} forment des amas`, text: `Sur ce plan, les points se regroupent en paquets séparés (scagnostic « Amas » = ${fr(s.clumpy)}). Des sous-populations sont probables.`, mini: { type: "scatter", i: s.i, j: s.j }, act: { pair: [s.i, s.j] } });
      if (s.striated >= 0.35) add({ kind: "shape", score: 0.3 + 0.3 * s.striated, key: `pair${s.i}-${s.j}`, vars: [s.i, s.j], title: `${res.vars[s.i]} × ${res.vars[s.j]} : nuage strié`, text: `Les points s'alignent en bandes (scagnostic « Strié » = ${fr(s.striated)}) : au moins une des deux variables ne prend que quelques valeurs.`, mini: { type: "scatter", i: s.i, j: s.j }, act: { pair: [s.i, s.j] } });
    });
  }
  // variables : asymetrie, bimodalite, valeurs manquantes
  table.columns.forEach(c => {
    const raw = table.rows.map(r => r[c]), isQ = table.numeric instanceof Set && !table.numeric.has(c), num = isQ ? [] : raw.map(toNum), fin = num.filter(Number.isFinite), nn = raw.filter(v => v !== null && v !== undefined).length;
    const missPct = (1 - nn / raw.length) * 100; if (missPct >= 3) add({ kind: "missing", score: clamp(missPct / 30, 0.3, 0.85), title: `${c} : ${pc(missPct, 0)} de valeurs manquantes`, text: `${raw.length - nn} lignes n'ont pas de valeur. Par défaut elles sont exclues ; l'imputation par ACP itérative les garde sans fausser la structure.`, mini: { type: "gauge", v: missPct / 100 }, act: { tab: "profil" } });
    // forme de la distribution : estimee sur 50 000 valeurs tirees au hasard au-dela (asymetrie, bimodalite, quantiles : erreur negligeable)
    if (fin.length < 12 || fin.length < 0.9 * nn) return; const d = describe(fin.length > 50000 ? sampleRows(fin.length, 50000, 79).map(i => fin[i]) : fin); if (d.uniq < 6) return;
    if (Math.abs(d.skew) >= 1) add({ kind: "skew", score: clamp(0.35 + Math.abs(d.skew) / 6, 0, 0.85), key: `var${c}`, title: `${c} est très asymétrique`, text: `Asymétrie = ${fr(d.skew)} : quelques valeurs ${d.skew > 0 ? "très élevées" : "très basses"} tirent la moyenne (${fmtNum(d.mean)}) loin de la médiane (${fmtNum(d.med)}).${d.skew > 0 && d.min >= 0 ? " Un passage au logarithme rendrait l'analyse plus équilibrée." : ""}`, mini: { type: "hist", col: c }, act: d.skew > 0 && d.min >= 0 ? { transform: [c, "log"] } : { tab: "profil" } });
    if (d.bc > 0.555 && fin.length >= 30 && Math.abs(d.skew) < 1.2) add({ kind: "bimodal", score: clamp(0.35 + (d.bc - 0.555) * 2, 0, 0.8), key: `var${c}`, title: `${c} semble bimodale`, text: `Coefficient de bimodalité = ${fr(d.bc, 3)} (> 0,555) : la distribution a probablement deux bosses, signe de deux populations mélangées.`, mini: { type: "hist", col: c }, act: { tab: "profil" } });
  });
  // atypiques
  if (res.method === "ACP" && res.nAxes < res.q) { const dg = diagCache(res), ratio = i => Math.max(dg.T2[i] / dg.ucT, dg.ucQ ? dg.Q[i] / dg.ucQ : 0);
    const fl = range(res.n).filter(i => ratio(i) > 1).sort((a, b) => ratio(b) - ratio(a)), strong = fl.filter(i => ratio(i) > 2), expect = res.n * (1 - 0.95 * 0.95);
    if (strong.length) add({ kind: "outlier", score: clamp(0.55 + Math.log10(ratio(strong[0])) / 3, 0.55, 0.96), title: `${pl(strong.length, "individu très atypique", "individus très atypiques")}`, text: `${liste(strong.map(i => res.names[i]), 4)} dépasse${strong.length > 1 ? "nt" : ""} plus de deux fois la limite à 95 % (T² de Hotelling ou écart au modèle Q ; le plus extrême : ${fmtNum(ratio(strong[0]))} fois). Au total ${fl.length} individus dépassent la limite, pour environ ${fr(expect, 0)} attendus par hasard.`, mini: { type: "tq" }, act: { select: strong } });
    else if (fl.length > 1.5 * expect) add({ kind: "outlier", score: 0.45, title: `Plus d'atypiques que prévu`, text: `${fl.length} individus dépassent les limites à 95 % alors qu'environ ${fr(expect, 0)} seraient attendus par hasard : ${liste(fl.map(i => res.names[i]), 4)}.`, mini: { type: "tq" }, act: { select: fl } }); }
  // classes
  if (hc && res.method !== "AFC") add({ kind: "clusters", score: clamp(0.35 + hc.R2 * 0.6, 0, 0.92), title: `Les ${res.method === "ACM" ? "individus" : "individus"} forment ${hc.k} classes`, text: `Classification hiérarchique sur les ${pl(hc.dims, "axe")} retenus (Ward, consolidée par k-means) : ${pc(hc.R2 * 100, 0)} de l'inertie est expliquée par la partition. Tailles : ${hc.sizes.join(", ")}.`, mini: { type: "bars", data: hc.sizes.map((s, k) => ({ l: `C${k + 1}`, v: s, c: `var(--g${k % 10 + 1})` })) }, act: { tab: "classes" } });
  // groupes (variable de couleur)
  if (res.method === "ACP" && res.groups) { const an = res.vars.map((v, j) => ({ j, ...anova(res.X.map(r => r[j]), res.groups) })).sort((a, b) => b.eta2 - a.eta2);
    if (an[0].eta2 >= 0.3) add({ kind: "groups", score: clamp(an[0].eta2, 0.3, 0.95), title: `${res.color} explique ${pc(an[0].eta2 * 100, 0)} de ${res.vars[an[0].j]}`, text: `Rapport de corrélation η² = ${fr(an[0].eta2, 3)} (test F, p ${an[0].p < 0.001 ? "< 0,001" : "= " + fr(an[0].p, 3)}). ${an[1] && an[1].eta2 >= 0.3 ? `Suivi de ${res.vars[an[1].j]} (η² = ${fr(an[1].eta2, 2)}).` : ""}`, mini: { type: "groupmeans", j: an[0].j }, act: { enc: `var:${res.vars[an[0].j]}` } }); }
  if (res.method === "ACM") { const pairs = []; for (let a = 0; a < res.K; a++) for (let b = a + 1; b < res.K; b++) pairs.push({ a, b, ...cramerV(res.answers.map(r => r[a]), res.answers.map(r => r[b])) });
    pairs.sort((x, y) => y.v - x.v).slice(0, 3).filter(o => o.v >= 0.3).forEach(o => add({ kind: "assoc", score: clamp(o.v, 0.3, 0.9), title: `${res.vars[o.a]} et ${res.vars[o.b]} sont liées`, text: `V de Cramér = ${fr(o.v)} (χ² = ${fr(o.chi2, 1)}, p ${o.p < 0.001 ? "< 0,001" : "= " + fr(o.p, 3)}) : connaître l'une renseigne fortement sur l'autre.`, mini: { type: "bars", data: [{ l: "V", v: o.v, c: "var(--a2)" }] }, act: { tab: "variables" } }));
    const rare = res.mods.filter((m, j) => res.eff[j] / res.n < 0.05); if (rare.length) add({ kind: "missing", score: 0.4, title: `${pl(rare.length, "modalité rare", "modalités rares")}`, text: `${liste(rare, 3)} concerne${rare.length > 1 ? "nt" : ""} moins de 5 % des individus : ${rare.length > 1 ? "elles peuvent" : "elle peut"} tirer un axe à ${rare.length > 1 ? "elles" : "elle"} seule${rare.length > 1 ? "s" : ""}.`, mini: { type: "gauge", v: rare.length / res.M }, act: { tab: "synthese" } }); }
  if (res.method === "AFC") { let mx = [0, 0], mn = [0, 0]; res.ratio.forEach((row, i) => row.forEach((x, j) => { if (x > res.ratio[mx[0]][mx[1]]) mx = [i, j]; if (x < res.ratio[mn[0]][mn[1]]) mn = [i, j]; }));
    add({ kind: "assoc", score: 0.75, title: `${res.rowL[mx[0]]} × ${res.colL[mx[1]]} : +${Math.round((res.ratio[mx[0]][mx[1]] - 1) * 100)} %`, text: `L'association la plus forte : ${Math.round((res.ratio[mx[0]][mx[1]] - 1) * 100)} % de plus qu'attendu sous l'indépendance. À l'inverse, ${res.rowL[mn[0]]} × ${res.colL[mn[1]]} est ${Math.round((1 - res.ratio[mn[0]][mn[1]]) * 100)} % en dessous.`, mini: { type: "bars", data: res.colL.map((c, j) => ({ l: c.slice(0, 6), v: res.ratio[mx[0]][j] - 1, c: res.ratio[mx[0]][j] >= 1 ? "var(--pos)" : "var(--neg)" })) }, act: { tab: "synthese" } }); }
  // deduplication : une paire ou une variable n'apparait que dans son meilleur insight de chaque type
  const seen = new Set(), perKind = {}, cap = { nonlin: 3, curve: 2, skew: 3, bimodal: 2, shape: 2, corr: 3, indirect: 2, redund: 2, missing: 3, assoc: 3 };
  const varUse = {};   // une variable n'apparait qu'une fois par type de forme (evite qu'une variable extreme monopolise la liste)
  return I.sort((a, b) => b.score - a.score).filter(o => { const k = o.key ? o.kind + o.key : null; if (k && seen.has(k)) return false;
    if (o.vars) { if (o.vars.some(v => varUse[o.kind + v])) return false; o.vars.forEach(v => (varUse[o.kind + v] = 1)); }
    if (k) seen.add(k); perKind[o.kind] = (perKind[o.kind] || 0) + 1; return perKind[o.kind] <= (cap[o.kind] ?? 9); });
}
const fmtNum = x => fr(x, Math.abs(x) >= 100 ? 0 : Math.abs(x) >= 10 ? 1 : 2);
